### ISSUE TITLE
abcAccount.updateSettings() exists?

### ISSUE THREAD

**Issue by cipherzzz** [Airbitz/edge-currency-bitcoin#19]
Hey guys, looking forward to integrating with your product!  I have a question...

When I look at your **README** and you mention we can do the following:

```
This plugin exposes the following otherSettings which can be set using abcAccount.updateSettings()

{
  enableOverrideServers: boolean,
  electrumServers: Array<Array[String, String]>,
  feeInfoServer: String
}
```

*I don't see the implementation of this to override the electrumServers(currencyEngine.js)

```
// ------------------------------------------------------------------------
  // Public API
  // ------------------------------------------------------------------------
  updateSettings (settings: any): void {
    // TODO: Implement this
  }
```

How do we do this? I am assuming that we would pass in the ```updatedSettings``` into the ```abcAccount.updateSettings(updatedSettings)``` - could I get an example? I would like to work on the plugin based on my own local electrum server...

**Comment by swansontec** [comment]
Sorry, but we haven't gotten around to implementing that part of the interface yet.

**Comment by paullinator** [comment]
I assume you’re asking WRT a Decred plugin. It shouldn’t be necessary to call this routine to add Decred support. You just manually add some electrum servers inside the code the way LTC and Dash are implemented.

**Comment by cipherzzz** [comment]
Yeah, I added my electrum server as a localhost, but when I run the
edge-react-Gui it hits this URL for the list instead.

https://info1.edgesecure.co:8444/v1/electrumServers/DCR

**Comment by paullinator** [comment]
Hmm. That should only be to override the existing servers in code, but if that fails, the ones in the code should prevail. Are you seeing otherwise?

**Comment by cipherzzz** [comment]
I wasn't seeing any localhost electrum servers being called or exceptions
thrown. I'll check on Monday, thanks for the feedback

**Comment by paullinator** [comment]
Ok. @thehobbit85 would know the code best. @thehobbit85 can you comment on where in the code the fallback logic is to use the hardcoded Electrum nodes if the info1 server query fails.

**Comment by thehobbit85** [comment]
https://github.com/Airbitz/edge-currency-bitcoin/blob/master/src/plugin/pluginState.js#L66
